name: Output parameters

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: env-setup
      id: env-setup
      env:
        env_token: production
        env_domain: example.com
      run: |
        {
          echo "### Workflow variables"
          echo "| Variable   | Value       |"
          echo "| ---------- | ----------- |"
          echo "| env_token  | $env_token  |"
          echo "| env_domain | $env_domain |"
        } >> $GITHUB_STEP_SUMMARY
    - run: |
        echo "${{ steps.env-setup.outputs.env_token }}"
        echo "${{ steps.env-setup.outputs.env_domain }}"
